### ISSUE TITLE
sinatra-flash not working with shotgun

### ISSUE THREAD

**Issue by fetmar** [sklise/sinatra-warden-example#5]
See issue at https://github.com/SFEley/sinatra-flash/issues/7

I believe with the versions in your `Gemfile` it works just as you say, but I had newer versions of everything and it only worked with `rackup`. 

Thanks for the awesome example.

**Comment by JimiSpire** [comment]
Hi, I believe this issue is still open. I'm experiencing the same problem with flash and shotgun and since your exemple really helped me, i guess it would be neat to have it fixed.

Thanks a bunch and great work!

**Comment by sklise** [comment]
Hey @JimiSpire and @fetmar I finally fixed this.

I found an answer on [StackOverflow](http://stackoverflow.com/questions/5631862/sinatra-and-session-variables-which-are-not-being-set) and updated the readme and code to make it work.
