### ISSUE TITLE
Misleading example for user authenticate

### ISSUE THREAD

**Issue by science** [sklise/sinatra-warden-example#7]
First off, this is a very useful project - thank you.

The small nit I want to raise is that you propose a user authentication method that implies storage of a plaintext password: `if self.password == attempted_password`

I realize the point of this example is to streamline the description. So perhaps just put a comment on this line `# DO NOT use this in a real application - always encrypt your passwords in a production app (if you use ActiveRecord see "has_secure_password" feature).`

**Comment by sklise** [comment]
Hey @science you are totally right, sorry for the terse initial response. I wanted this repo to help people learn and breezing over how BCrypt works was not helping.

I've updated the code in [`model.rb](https://github.com/sklise/sinatra-warden-example/blob/master/model.rb#L13-L17) to explain what is happening.

**Comment by science** [comment]
Great explanation! Thanks for taking that on..
