### ISSUE TITLE
Greetings from the future (3 hiccups for ppl using this example)

### ISSUE THREAD

**Issue by muziejus** [sklise/sinatra-warden-example#8]
There are three small hiccups (at least) in this code that made it not work in my application:

1. Generally in sinatra, you can use `params[:symbol]`. The Warden strategy, however, requires `params["string"]`.

1. flashing did not work for some reason until I changed `env['warden'].message` to `env['warden.options'][:message]`.

1. DataMapper yells at me when I `include BCrypt`. Removing that worked fine, and the password is still hashed. 

These issues came up with:
* bcrypt-ruby 3.1.5 (vs. 3.0.1 in this example)
* dm-core 1.2.0 (as in this example)
* rack 1.6.4 (vs. 1.5.2)
* sinatra 1.4.6 (vs. 1.3.4)
* sinatra-flash 0.3.0 (as in this example)
* warden 1.2.3 (as in this example)

I imagine versions may have been causing some of the problems, but I'm not certain. Either way, than you very much for this example!

**Comment by sklise** [comment]
What version of Ruby are you using? I'm pretty sure that I wrote this with 1.8.X or 1.9.X, and running now with 2.0.0 I'm also getting errors, will do some debugging and update!

**Comment by muziejus** [comment]
Haha, of course! Sorry for forgetting. ruby 2.2.3.

My implementation is at [nyscapes/nywalker](http://github.com/nyscapes/nywalker).

**Comment by muziejus** [comment]
Incidentally, my `User` class uses `username` as a key in addition to `id`, meaning that `User.get(id)` also causes an error. It demands `User.get(id, username)`, but I decided `User.first(id: id)` works perfectly fine.

**Comment by sklise** [comment]
Thanks for the notes! The `data_mapper` gem hasn't been updated since 2011, and when I try to use a ruby over 2.2.0, the required `json` gem won't compile. So going to switch out `data_mapper` for `dm-core` and the individual gems, which very luckily have more recent updates.

**Comment by sklise** [comment]
Ah yes, if you have multiple keys in your `User` table, then you'd have to pass values for each of them to the `.get()` method.

**Comment by sklise** [comment]
Just pushed some fixes, lemme know if they work for you?

**Comment by muziejus** [comment]
I managed to get a system up and running... my issue was more a heads up. We got to the same place in slightly different ways, it seems, but everything works, so great!

I worry about data_mapper. It's so much more transparent to me in its soft touch than activerecord. Let's hope it stays active!

**Comment by sklise** [comment]
:+1: :smile:
